---
- name: install nginx
  apt:
    name: nginx
  tags:
    - nginx:install

- name: configure main nginx.conf
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
    force: yes
  notify:
    - check nginx configuration
    - restart nginx
  tags:
    - nginx:config:main

- name: ensure nginx is started enabled at startup
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - nginx:service

# vim: set et fenc=utf-8 ft=ansible sts=2 sw=2 ts=8 tw=0 :
