---
dist: trusty
sudo: required

language: python
python:
- "2.7"

services:
- docker

before_install:
- deactivate
- sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32 40976EAF437D05B5
- sudo apt-get update -qq
- sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine

install:
- sudo pip install ansible
- sudo pip install docker-py
- sudo pip install molecule
- ansible --version
- molecule --version

script:
- ansible-playbook -i inventory playbook.yml
