---
bluegreen: yes
default_color: green
check_mode: no
app_name: www
app_repo:
app_version: latest
app_instances_count: 2
app_hostname: localhost

# vim: set et fenc= ft=ansible sts=2 sw=2 ts=2 tw=0 :
