---
bluegreen: True
default_color: green
check_mode: False
app_name: www
app_repo:
app_version: latest
app_instances_count: 2
app_hostname: localhost
app_private_registry: False

first_run: True

# vim: set et fenc= ft=ansible sts=2 sw=2 ts=2 tw=0 :
