---
- name: store host facts
  blockinfile:
    dest: /etc/ansible/facts.d/{{ app_name }}.fact
    create: yes
    block: |
      [{{ app_name }}]
      env_color: {{ next_color }}
      instances_count: {{ app_instances_count }}
      version: {{ app_version }}

- name: stop old env containers
  docker_container:
    name: "{{ app_name }}_{{ current_color }}_{{ item }}"
    state: stopped
  with_sequence: count={{ current_count }}
  ignore_errors: yes
  when: (not first_run) and (app_version != current_version)
  tags:
    - skip_ansible_lint

# vim: set et fenc= ft=ansible sts=2 sw=2 ts=2 tw=0 :
