---
- name: check first run
  set_fact: first_run=yes
  when: ansible_local[app_name] is not defined

- name: determine current color
  set_fact: current_color={{ ansible_local[app_name][app_name].env_color }}
  when: ansible_local[app_name] is defined

- name: determine current count of instances
  set_fact: current_count={{ ansible_local[app_name][app_name].instances_count }}
  when: ansible_local[app_name] is defined

- name: set current color if not in facts
  set_fact: current_color={{ default_color }}
  when: first_run is defined

- name: determine current count of instances if not in facts
  set_fact: current_count={{ app_instances_count }}
  when: first_run is defined

- name: set new color
  set_fact: next_color="blue"
  when: current_color == "green"

- name: set new color
  set_fact: next_color="green"
  when: current_color == "blue"

# vim: set et fenc= ft=ansible sts=0 sw=2 ts=2 tw=0 :
