---
# workaround for docker-engine dependencies problem
- name: upgrade system
  yum: name=* state=latest
  tags:
    - common:upgrade
    - skip_ansible_lint

- name: ensure facts.d dir exists
  file: path=/etc/ansible/facts.d state=directory
  tags:
    - common:facts

- name: put dummy fact to local facts dir
  file: path=/etc/ansible/facts.d/dummy.fact state=touch
  tags:
    - common:facts

- name: enable ipv4 forwarding
  sysctl:
    name: "net.ipv4.ip_forward"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  tags:
    - common:forwarding

# vim: set et fenc= ft=ansible sts=2 sw=2 ts=2 tw=0 :
