---
- name: docker repository
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo

- name: install docker-engine
  yum: name=docker-engine

- name: install epel-release
  yum: name=epel-release

- name: install deps
  yum: name="{{ item }}"
  with_items:
    - python-pip
    - git

# incorrect version comparison workaround
- name: install docker-py
  pip: name=docker-py version=1.9.0

- name: check docker-compose bin file presence
  stat: path=/usr/local/bin/docker-compose
  register: dockercompose

- name: install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ dockercompose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: "a+x"
  when: dockercompose.stat.exists == false

- name: install docker-custodian
  pip: name='git+https://github.com/Yelp/docker-custodian.git' editable=false

- name: ensure docker.service.d dir exists
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: enable docker service
  service: name=docker enabled=yes

- name: setup overlay storage driver
  include: overlay.yml
  when: docker_use_overlay

- name: start docker service
  service: name=docker state=started

# vim: set et fenc=utf-8 ft=ansible sts=2 sw=2 ts=2 tw=0 :
