---
- name: docker repository
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo

- name: install docker-engine
  yum: name=docker-engine

- name: install epel-release
  yum: name=epel-release

- name: install deps
  yum: name="{{ item }}"
  with_items:
    - python-pip
    - git

# incorrect version comparison workaround
- name: install docker-py
  pip: name=docker-py version=1.9.0

- name: install docker-compose
  pip: name=docker-compose

- name: install docker-custodian
  pip: name='git+https://github.com/Yelp/docker-custodian.git' editable=false

- name: ensure docker.service.d dir exists
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: enable docker service
  service: name=docker enabled=yes

- name: setup overlay storage driver
  include: overlay.yml
  when: docker_use_overlay

- name: start docker service
  service: name=docker state=started

# vim: set et fenc=utf-8 ft=ansible sts=2 sw=2 ts=2 tw=0 :
